development:
  adapter: postgresql
  username: indymedia
  encoding: unicode
  pool: 5
  database: indymedia_dev
  template: template0

test:
  adapter: postgresql
  username: indymedia
  encoding: unicode
  pool: 5
  database: indymedia_test
  template: template0

production:
  adapter: postgresql
  username: indymedia
  encoding: unicode
  pool: 5
  database: indymedia
  template: template0

# NB: We're using 'template: template0' so that we can use
# our own database encoding scheme, eg. unicode as opposed to ascii.