production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
  auto_commit_after_request: false

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
  auto_commit_after_request: false

development_with_caching:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
  auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
  auto_commit_after_request: false